apiVersion: v1
kind: List
items:

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-config-lago-kube-host0
   namespace: default
  data:
   config.properties: |-
    node_name=lago-kube-host0
    isolation=ssh
    power_management=
    recovery=

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-config-lago-kube-host1
  data:
   config.properties: |-
    node_name=lago-kube-host1
    isolation=fc-off
    power_management=eaton-off eaton-on
    recovery=fc-on

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-template-fc-switch-brocade
   namespace: default
  data:
   template.properties: |-
          name=fc_switch_brocade
          agent_name=fence_brocade
          ipaddr=192.168.1.2
          password=brocade_password
          username=brocade_admin

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-template-apc-pdu
   namespace: default
  data:
   template.properties: |-
          name=apc_pdu
          agent_name=fence_apc_snmp
          must_sucess=yes
          ipaddr=192.168.1.3
          password=apc_password
          username=apc_admin

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-template-eaton-pdu
   namespace: default
  data:
   template.properties: |-
          name=eaton_pdu
          agent_name=fence_eaton_snmp
          must_sucess=yes
          ipaddr=192.168.1.4
          password=eaton_password
          username=eaton_admin
          snmp-priv-prot=AES
          snmp-priv-passwd=eaton_snmp_passwd
          snmp-sec-level=authPriv
          inet4-only=true

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-fc-off-lago-kube-host0
   namespace: default
  data:
   method.properties: |
          template=fence-method-template-fc-switch-brocade
          plug=1

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-fc-on-lago-kube-host0
   namespace: default
  data:
   method.properties: |
          template=fence-method-template-fc-switch-brocade
          plug=1

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-fc-off-lago-kube-host1
   namespace: default
  data:
   method.properties: |
          template=fence-method-template-fc-switch-brocade
          plug=2

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-fc-on-lago-kube-host1
   namespace: default
  data:
   method.properties: |-
          template=fence-method-template-fc-switch-brocade
          plug=2

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-eaton-off-lago-kube-host0
   namespace: default
  data:
   method.properties: |-
        template=fence-method-template-eaton-pdu
        plug=1
        action=off

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-eaton-on-lago-kube-host0
   namespace: default
  data:
   method.properties: |-
        template=fence-method-template-eaton-pdu
        plug=1
        action=on

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-eaton-off-lago-kube-host1
   namespace: default
  data:
   method.properties: |-
        template=fence-method-template-eaton-pdu
        plug=2
        action=off

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-eaton-on-lago-kube-host1
   namespace: default
  data:
   method.properties: |-
        template=fence-method-template-eaton-pdu
        plug=2
        action=on


- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-ssh-lago-kube-host0
   namespace: default
  data:
   method.properties: |-
     agent_name=ssh
     node_name=lago-kube-host0

- kind: ConfigMap
  apiVersion: v1
  metadata:
   name: fence-method-ssh-lago-kube-host1
   namespace: default
  data:
   method.properties: |-
     agent_name=ssh
     node_name=lago-kube-host1
